### ISSUE TITLE
Improve the display of the images pannel

### ISSUE THREAD

**Issue by mabecabrera** [SpeciesFileGroup/taxonpages#153] opened 2023-09-21 16:15 UTC
### Feature or enhancement

The first idea was to show the same info and in the order it is shown in Browse OTU in a new Tab in the publica pages.

<img width="1171" alt="image" src="https://github.com/SpeciesFileGroup/taxonpages/assets/63611746/f61f2fd3-8f85-4401-8935-e4190bc3302c">

To have a tab specially for the specimens. But maybe that can be done some way in the same panel of the overview once we open it.
Right now we have the images but no specific order, all specimens mixed with each other.

<img width="1680" alt="image" src="https://github.com/SpeciesFileGroup/taxonpages/assets/63611746/d4a247fd-fc6f-41f6-b1f3-e726382540b7">

### Location

Taxon pages

### Your role

Editor Assitant

**Comment by mabecabrera** [comment] 2023-09-21 16:16
A new feature for comparing images would be awsome but I think that would be best to have has a task in Taxon Works. And have a link in the public page to go to the Practice Database to that task.

**Comment by mabecabrera** [comment] 2023-09-21 17:23
From other issue, other OSF user commented: <Source of images should be complete, incl repository - maybe inside the pic? >

**Comment by klausriede** [comment] 2023-09-22 10:39
indeed! sources should be visible when hovering over pic, clicking on pic (I think this is now completed) but particularly when you DOWNLOAD the image source info should be stored somehwere, maybe at bottomline

**Comment by mabecabrera** [comment] 2023-10-04 17:05
Later we could add in the TW enviroment to have a task for comparing images like we did in SFS.
<img width="1277" alt="image" src="https://github.com/SpeciesFileGroup/taxonpages/assets/63611746/8b3cc7fa-9186-40f6-8627-a2c4d34e59b9">

**Comment by mjy** [comment] 2024-10-15 20:58
Duplicate of #13

**Closed by mjy** 2024-10-15 20:58 UTC
Labels: enhancement
